import React, { useState } from 'react';

export default function FaqSection() {
  const [openIndex, setOpenIndex] = useState(0);

  const faqs = [
    {
      q: "How does Career GPS automate my job applications?",
      a: "Career GPS deploys an integrated fleet of autonomous agents that monitor real-time job openings across major platforms. Once a high-affinity role is matched to your background, the system dynamically analyzes the job description, recalibrates your resume bullets with semantic ATS keywords, and pre-populates application materials for high-velocity submission."
    },
    {
      q: "Will my resume pass Applicant Tracking Systems (ATS)?",
      a: "Yes. Every resume generated by Career GPS is pre-audited against our 90-point ATS compliance benchmark. We eliminate unparseable columns, non-standard fonts, and missing semantic keywords to ensure your profile ranks in the top 5% of recruiter review dashboards."
    },
    {
      q: "What is the role of the Human Consultant in the Elite plan?",
      a: "While our AI agents handle data analysis, formatting, and high-volume background execution, your dedicated US-based human consultant provides high-stakes strategic guidance. They lead 1:1 strategy calls, conduct realistic mock interviews, review sensitive outreach messages, and direct salary negotiations."
    },
    {
      q: "Why not buy separate AI tools like ChatGPT or resume builders?",
      a: "Paying for separate ATS scanners, resume tailors, outreach message templates, LinkedIn indexers, and application trackers quickly adds up to hundreds of dollars a month in disconnected tools. Career GPS unites everything into a single, cohesive operating system where every piece shares data to optimize your target pipeline."
    },
    {
      q: "Is Career GPS free to try?",
      a: "Yes! Our Starter tier is completely free. It includes one full Career Health Analysis, an ATS diagnostic scan, 5 AI resume optimizations, and baseline salary benchmarking. It requires no credit card to start."
    },
    {
      q: "Can I upgrade or cancel later?",
      a: "Absolutely. You can start with our free assessment, get your report, and upgrade to the AI Plan or the Elite (AI + Human) plan whenever you are ready to launch your background job search campaigns. All plans are month-to-month and can be canceled anytime with a single click."
    }
  ];

  return (
    <section className="section faq-section" id="faq" aria-labelledby="faq-heading">
      <div className="container faq-container">
        
        <div className="text-center" style={{'marginBottom': '50px'}}>
          <div className="badge badge-purple">
            <span className="pulse-dot purple" aria-hidden="true"></span>
            Frequently Asked Questions
          </div>
          <h2 className="section-heading" id="faq-heading">
            Got Questions?<br />
            <span className="gradient-text">We Have Answers.</span>
          </h2>
          <p className="section-subtext">
            Everything you need to know about our AI agents, human coaching, and job search operating system.
          </p>
        </div>

        <div className="faq-list">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div key={idx} className={`faq-card glass-panel ${isOpen ? 'open' : ''}`}>
                <button 
                  type="button"
                  className="faq-question-btn" 
                  aria-expanded={isOpen}
                  onClick={() => setOpenIndex(prev => prev === idx ? -1 : idx)}
                >
                  <span>{faq.q}</span>
                  <svg 
                    className="faq-chevron" 
                    width="18" 
                    height="18" 
                    viewBox="0 0 24 24" 
                    fill="none" 
                    stroke="currentColor" 
                    strokeWidth="2.5"
                    style={{ transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.25s ease' }}
                  >
                    <polyline points="6 9 12 15 18 9" />
                  </svg>
                </button>
                <div 
                  className="faq-answer-panel" 
                  style={{ display: isOpen ? 'block' : 'none' }}
                >
                  <p>{faq.a}</p>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
